# Default values for modernpets.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: registry.ng.bluemix.net/davewakeman # Ex: registry.ng.bluemix.net/mynamespace
  pullPolicy: Always

ingress:
  enabled: true
  hosts:
    - jpetstore.dw-petstore-03.us-south.containers.appdomain.cloud # Ex: jpetstore.myclustername.us-south.containers.mybluemix.net